#ifndef ID_OSD2_1_MENU_BACK_TRACK_INFO_H
#define ID_OSD2_1_MENU_BACK_TRACK_INFO_H

/* Group ID 1 */
#define ID_OSD2_1_MENU_BACK_TRACK_1_FONT_SIZE 96
#define ID_OSD2_1_MENU_BACK_TRACK_1_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_1_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_1_START_INDEX 89
#define ID_OSD2_1_MENU_BACK_TRACK_1_MAX_FONT_NUM 3

extern void* code ID_OSD2_1_MENU_BKTC_1_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_1_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_1_RADAR_B_TAB[];

/* Group ID 2 */
#define ID_OSD2_1_MENU_BACK_TRACK_2_FONT_SIZE 96
#define ID_OSD2_1_MENU_BACK_TRACK_2_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_2_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_2_START_INDEX 98
#define ID_OSD2_1_MENU_BACK_TRACK_2_MAX_FONT_NUM 4

extern void* code ID_OSD2_1_MENU_BKTC_2_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_2_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_2_RADAR_B_TAB[];

/* Group ID 3 */
#define ID_OSD2_1_MENU_BACK_TRACK_3_FONT_SIZE 96
#define ID_OSD2_1_MENU_BACK_TRACK_3_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_3_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_3_START_INDEX 102
#define ID_OSD2_1_MENU_BACK_TRACK_3_MAX_FONT_NUM 3

extern void* code ID_OSD2_1_MENU_BKTC_3_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_3_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_3_RADAR_B_TAB[];

/* Group ID 4 */
#define ID_OSD2_1_MENU_BACK_TRACK_4_FONT_SIZE 192
#define ID_OSD2_1_MENU_BACK_TRACK_4_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_4_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_4_START_INDEX 186
#define ID_OSD2_1_MENU_BACK_TRACK_4_MAX_FONT_NUM 6

extern void* code ID_OSD2_1_MENU_BKTC_4_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_4_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_4_RADAR_B_TAB[];

/* Group ID 5 */
#define ID_OSD2_1_MENU_BACK_TRACK_5_FONT_SIZE 192
#define ID_OSD2_1_MENU_BACK_TRACK_5_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_5_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_5_START_INDEX 192
#define ID_OSD2_1_MENU_BACK_TRACK_5_MAX_FONT_NUM 6

extern void* code ID_OSD2_1_MENU_BKTC_5_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_5_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_5_RADAR_B_TAB[];

/* Group ID 6 */
#define ID_OSD2_1_MENU_BACK_TRACK_6_FONT_SIZE 192
#define ID_OSD2_1_MENU_BACK_TRACK_6_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_6_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_6_START_INDEX 198
#define ID_OSD2_1_MENU_BACK_TRACK_6_MAX_FONT_NUM 6

extern void* code ID_OSD2_1_MENU_BKTC_6_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_6_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_6_RADAR_B_TAB[];

/* Group ID 7 */
#define ID_OSD2_1_MENU_BACK_TRACK_7_FONT_SIZE 192
#define ID_OSD2_1_MENU_BACK_TRACK_7_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_7_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_7_START_INDEX 204
#define ID_OSD2_1_MENU_BACK_TRACK_7_MAX_FONT_NUM 9

extern void* code ID_OSD2_1_MENU_BKTC_7_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_7_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_7_RADAR_B_TAB[];

/* Group ID 8 */
#define ID_OSD2_1_MENU_BACK_TRACK_8_FONT_SIZE 192
#define ID_OSD2_1_MENU_BACK_TRACK_8_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_8_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_8_START_INDEX 213
#define ID_OSD2_1_MENU_BACK_TRACK_8_MAX_FONT_NUM 20

extern void* code ID_OSD2_1_MENU_BKTC_8_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_8_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_8_RADAR_B_TAB[];

/* Group ID 9 */
#define ID_OSD2_1_MENU_BACK_TRACK_9_FONT_SIZE 192
#define ID_OSD2_1_MENU_BACK_TRACK_9_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_9_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_9_START_INDEX 233
#define ID_OSD2_1_MENU_BACK_TRACK_9_MAX_FONT_NUM 16

extern void* code ID_OSD2_1_MENU_BKTC_9_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_9_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_9_RADAR_B_TAB[];

/* Group ID 10 */
#define ID_OSD2_1_MENU_BACK_TRACK_10_FONT_SIZE 96
#define ID_OSD2_1_MENU_BACK_TRACK_10_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_10_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_10_START_INDEX 105
#define ID_OSD2_1_MENU_BACK_TRACK_10_MAX_FONT_NUM 9

extern void* code ID_OSD2_1_MENU_BKTC_10_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_10_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_10_RADAR_B_TAB[];

/* Group ID 11 */
#define ID_OSD2_1_MENU_BACK_TRACK_11_FONT_SIZE 96
#define ID_OSD2_1_MENU_BACK_TRACK_11_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_11_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_11_START_INDEX 114
#define ID_OSD2_1_MENU_BACK_TRACK_11_MAX_FONT_NUM 8

extern void* code ID_OSD2_1_MENU_BKTC_11_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_11_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_11_RADAR_B_TAB[];

/* Group ID 12 */
#define ID_OSD2_1_MENU_BACK_TRACK_12_FONT_SIZE 96
#define ID_OSD2_1_MENU_BACK_TRACK_12_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_12_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_12_START_INDEX 158
#define ID_OSD2_1_MENU_BACK_TRACK_12_MAX_FONT_NUM 12

extern void* code ID_OSD2_1_MENU_BKTC_12_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_12_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_12_RADAR_B_TAB[];

/* Group ID 13 */
#define ID_OSD2_1_MENU_BACK_TRACK_13_FONT_SIZE 96
#define ID_OSD2_1_MENU_BACK_TRACK_13_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_13_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_13_START_INDEX 45
#define ID_OSD2_1_MENU_BACK_TRACK_13_MAX_FONT_NUM 44

extern void* code ID_OSD2_1_MENU_BKTC_13_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_13_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_13_RADAR_B_TAB[];

/* Group ID 14 */
#define ID_OSD2_1_MENU_BACK_TRACK_14_FONT_SIZE 96
#define ID_OSD2_1_MENU_BACK_TRACK_14_MENU_WIDTH 50
#define ID_OSD2_1_MENU_BACK_TRACK_14_MENU_HEIGHT 20
#define ID_OSD2_1_MENU_BACK_TRACK_14_START_INDEX 170
#define ID_OSD2_1_MENU_BACK_TRACK_14_MAX_FONT_NUM 3

extern void* code ID_OSD2_1_MENU_BKTC_14_OBJECT_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_14_RADAR_F_TAB[];
extern void* code ID_OSD2_1_MENU_BKTC_14_RADAR_B_TAB[];

#endif
